# Generated by Django 3.2.18 on 2023-04-30 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('BSC', 'Basic'), ('ADV', 'Advanced'), ('EXT', 'Extreme')], default='BSC', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False, verbose_name='UUID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('artist', models.CharField(max_length=100, verbose_name='Artist')),
                ('tempo', models.FloatField(verbose_name='Tempo (BPM)')),
                ('length', models.IntegerField(verbose_name='Length (Ticks)')),
                ('banner_url', models.URLField(null=True, verbose_name='Banner Image URL')),
                ('preview_url', models.URLField(verbose_name='Preview Snippet URL')),
                ('song_url', models.URLField(verbose_name='Song Playback URL')),
            ],
        ),
        migrations.CreateModel(
            name='ChartEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.IntegerField()),
                ('type', models.CharField(choices=[('NOTE', 'Note'), ('HOLD', 'Hold'), ('BEAT', 'Beat'), ('MSUR', 'Measure'), ('STOP', 'End')], default='BEAT', max_length=4)),
                ('detail', models.IntegerField()),
                ('parent_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.chart')),
            ],
        ),
        migrations.AddField(
            model_name='chart',
            name='parent_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.level'),
        ),
    ]
